title: Data 6
description: Introduction to Computational Thinking with Data
author: UC Berkeley
baseurl: ~ # the subpath of your site, e.g. /blog
url: 'https://data6.org' # the base hostname & protocol for your site, e.g. http://example.com
#logo: "/assets/d6-header.png"
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: "just-the-docs/just-the-docs@v0.10.1"
plugins:
  - jekyll-remote-themecolor_scheme: light
  - jekyll-seo-tag
search_enabled: false
heading_anchors: true
permalink: pretty

# Collections for website data
collections:

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

